export enum ScannerState {
  CREATED = 'CREATED',
  SCANNING = 'SCANNING',
  VALIDATING = 'VALIDATING',
  REGISTERING = 'REGISTERING',
  READY = 'READY',
  FAILED = 'FAILED',
  STOPPED = 'STOPPED',
}
