export enum HttpStage {
  INCOMING_CONNECTION = 'INCOMING_CONNECTION',
  CREATE_REQUEST = 'CREATE_REQUEST',
  CREATE_RESPONSE = 'CREATE_RESPONSE',
  BUILD_CONTEXT = 'BUILD_CONTEXT',
  DELEGATE_FRAMEWORK = 'DELEGATE_FRAMEWORK',
  SEND_RESPONSE = 'SEND_RESPONSE',
  CLOSE_REQUEST = 'CLOSE_REQUEST',
}
