export enum SecurityStage {
  AUTHENTICATION = 'AUTHENTICATION',
  IDENTITY_VALIDATION = 'IDENTITY_VALIDATION',
  AUTHORIZATION = 'AUTHORIZATION',
  POLICY_EVALUATION = 'POLICY_EVALUATION',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
