export enum BootstrapStage {
  ENVIRONMENT = 'ENVIRONMENT',
  CONFIGURATION = 'CONFIGURATION',
  LOGGER = 'LOGGER',
  EXCEPTION_HANDLER = 'EXCEPTION_HANDLER',
  CONTAINER = 'CONTAINER',
  EVENT_BUS = 'EVENT_BUS',
  MODULE_REGISTRATION = 'MODULE_REGISTRATION',
  DEPENDENCY_VALIDATION = 'DEPENDENCY_VALIDATION',
  MODULE_STARTUP = 'MODULE_STARTUP',
  RUNTIME_READY = 'RUNTIME_READY',
}
