export enum RuntimeState {
  CREATED = 'CREATED',
  BOOTSTRAPPING = 'BOOTSTRAPPING',
  STARTING = 'STARTING',
  RUNNING = 'RUNNING',
  STOPPING = 'STOPPING',
  STOPPED = 'STOPPED',
  FAILED = 'FAILED',
}
