export enum RequestState {
  CREATED = 'CREATED',
  ROUTING = 'ROUTING',
  MIDDLEWARE = 'MIDDLEWARE',
  CONTROLLER = 'CONTROLLER',
  RESPONDING = 'RESPONDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
